id: P010757
initial_creation_type: ocr
source_metadata:
  id: bdr:W29673
  title: གསང་བ་སྙིང་པོའི་དཀའ་གནད་རྡོ་རྗེའི་མདུད་བཀྲལ་བའི་མེ་ལོང
  author: ''
  volumes:
    b77c7f60bc01432ea7c0d48067a53dd4:
      image_group_id: I5560
      title: ''
      volume_number: 1
      total_pages: 75
