id: I07A09EEC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T15:51:12+00:00'
last_modified: '2022-06-08T17:18:25.744850+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29673
  title: གསང་བ་སྙིང་པོའི་དཀའ་གནད་རྡོ་རྗེའི་མདུད་བཀྲལ་བའི་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    7F77:
      image_group_id: I5560
      title: ''
      total_pages: 75
      order: 1
      base_file: 7F77.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
